### ISSUE TITLE
oneDNN enablement and 8 bit GEMM support for s390x

### ISSUE THREAD

**Issue by edelsohn** [edelsohn/oneDNN#1]
Enable oneDNN for s390x and add 8 bit GEMM support optimized for s390x.

**Comment by parvit** [comment]
Hi, could you elaborate further about the requirements for this feature?

**Comment by quickwritereader** [comment]
https://github.com/oneapi-src/oneDNN/pull/1551

**Comment by quickwritereader** [comment]
https://github.com/oneapi-src/oneDNN/issues/1550

**Comment by edelsohn** [comment]
Resolved with pull request oneapi-src#1551 .

**Comment by ghost** [comment]
@edelsohn , please note that bountysource did not cashout this (and other) bounties.

https://github.com/bountysource/core/issues/1586

**Comment by edelsohn** [comment]
@abebeos Other bounty hunters have alerted me to the problem and I have been discussing the issue with Bountysource, The Blockchain Group (the current owner of Bountysource, a French company publicly traded on the EuroNext exchange), and the VC investors in The Blockchain Group for the past few months. The Blockchain Group repeatedly promises me that they will pay the bounties, but nothing happens.  The Blockchain Group commented that they have a concern about the accounts, but refuse to provide details or cooperate with me to investigate and resolve the concern. I have confirmed to them that the bounty hunters and bounty values are correct. The bounty funds have been correctly credited to the bounty hunters within the Bountysource system and IBM had paid the invoices to fund the bounties, so I and IBM have limited recourse.  It it curious why The Blockchain Group has not been able to fulfill these financial obligations of the bounty cashouts.

**Comment by ghost** [comment]
> It it curious why The Blockchain Group has not been able to fulfill these financial obligations of the bounty cashouts.

@edelsohn, as things stand, I believe one can safely assume that bountysource/Blockchain Group embezzles the escrowed bounty funds (e.g. using the money somewhere else, like investing/loosing-it in crypto etc.).

- https://github.com/bountysource/core/issues/1586
